### PR TITLE
Add post-processed graph analytics from networkX

### PR DESCRIPTION
**Pull request by curtislisle**
### Does this PR close any open issues?
Closes #  N/A

### Give a longer description of what this PR addresses and why it's needed

- This PR includes support for new API endpoints:  nodes_stats, nodes_filtered, edges_filtered.
- The first endpoint provides server-based calculation for betweenness centrality, node centrality, pagerank, and in/out node degree
- The second and third endoint enable extraction of a subgraph from a large graph by specifying a minimal threshold for in or out degrees of nodes to be included.  Current behavior returns some unconnected nodes.  Will look into this... 

### Are there any additional TODOs before this PR is ready to go?
Further testing by Jack. 

TODOs:
- [ ] Determine why `nodes_filtered` endpoint can return disconnected nodes

### CODE REVIEW

**Comment by curtislisle** [comment]
Second commit is to loo with Arango cursors to pull all nodes and edges.  Previous behavior (first commit) stopped at 1000.

**Review by waxlamp — COMMENTED** [review]
This is largely a style review, most (or all) of which can likely be solved by running your PR branch through the formatting commands.

```
docker-compose run --rm django tox -e format
```

will reformat your code to be in compliance with standard Python style (this command will modify your files in place, so be sure you have no outstanding edits to save of your own).

```
docker-compose run --rm django tox -e lint

```

will run the linter and show you linting failures not caught by the formatting step.

These commands should help to fix all the style issues (some of which I identified myself in my review; you should run these commands before addressing my comments, since those may become moot).

Let me know if you need help with this.

**Comment by curtislisle** [comment]
I replaced networkX with graph_tool.  The interface is the same.  Performance should be better on large graphs.  I pushed changes to this PR without style fixes yet, so Jack could look at it.  I will next address Roni's review comments before we decide to merge.

**Comment by curtislisle** [comment]
We opted to close this PR, in favor of running algorithms directly inside Arango via Pregel and AQL.

**Pull request closed without merging**
