### PR TITLE
Allow storing and retreiving of table column type metadata

### LINKED ISSUE #83: Store column types that are specified on upload for later retrieval
From Jake:
>We should probably store that data as a property (or association) of tables themselves.

### PR DESCRIPTION
**Pull request by JackWilb**
Closes #83

Adds table `/metadata` route to retrieve column types. 

This is in draft mode because I'm not able to save the types into the postgres db. The celery task completes without error, but the types just don't save. I'm looking for a quick code review to make sure I'm saving in a way that works with girder4.

### CODE REVIEW

**Comment by AlmightyYakob** [comment]
Thanks for all your work on this @JackWilb!

Pushed a few commits, with the following changes:
* Moved `ColumnTypeEnum` to live within `TableTypeAnnotation`, now using Django's `TextChoices` field.
* Re-created migrations to account for the above change
* Updated the endpoint name and serializer to remove the term "metadata", and instead focus on type annotations. Metadata is a broader concept which may be implemented down the line, so distinguishing the two is important imo.

**Comment by AlmightyYakob** [comment]
@JackWilb added a few more tests, which are self explanatory. Does how it looks now fit your needs?

**Comment by JackWilb** [comment]
@AlmightyYakob Looks good to me! I've tested locally and all the types are accessible through the endpoint. 

It seems like all the tests check for just number columns, should we expand the test to cover all the possible data types? Or is that partially covered elsewhere?

If the tests don't need to be updated, are you happy for me to merge? I think I'll need an approval

**Comment by AlmightyYakob** [comment]
> It seems like all the tests check for just number columns, should we expand the test to cover all the possible data types? Or is that partially covered elsewhere?

You're correct, that's mainly because the existing `airports_csv` fixture only added those column types. If that test file has columns which would exercise the other data types, then you're more than welcome to amend it.

> If the tests don't need to be updated, are you happy for me to merge? I think I'll need an approval

I'm good with it. If you don't want to update that fixture, then I'll give this an approval.

**Comment by JackWilb** [comment]
> > It seems like all the tests check for just number columns, should we expand the test to cover all the possible data types? Or is that partially covered elsewhere?
> 
> You're correct, that's mainly because the existing `airports_csv` fixture only added those column types. If that test file has columns which would exercise the other data types, then you're more than welcome to amend it.

I can't think of a way that we'd break the one of the other upload types and not the number type. I think that it's fine to go as is, so we don't have to create a whole new text fixture for this one case.

**Review by AlmightyYakob — APPROVED** [review]

**Pull request merged**
